---
- name: Creating a PHP Info for NGinx
  copy:
    dest: "/usr/share/nginx/html/info.php"
    content: |
      <?php
        phpinfo();
      ?>

- name: Ensure PHP packages are installed.
  package:
    name: "{{ php_packages + php_packages_extra }}"
    state: "{{ php_packages_state }}"
    enablerepo: "{{ php_enablerepo | default(omit, true) }}"
  notify: restart webserver
